#!/bin/bash
BENCH=s1423
HAPA=/home/frathoso/Dropbox/ASpring_2014/Capstone/atpg 
$HAPA/bin/atpg -D 2 -X R -b $HAPA/benchmarks/$BENCH.bench -Z > $HAPA/run/$BENCH.atpg.txt

wine $HAPA/bin/atalanta.exe $HAPA/benchmarks/$BENCH.bench -Z -l run/$BENCH.atalanta.txt > $HAPA/run/results.txt
